Repository buildo/wiro, pull requests merged in 2018-07, with the labels that each got.

#128 #127: Allow wiro user to access http headers (closes #127)
  clientAkkaHttp/src/main/scala/RequestBuilder.scala
  core/src/main/scala/models.scala
  examples/src/main/scala/Doghouse.scala
  serverAkkaHttp/src/main/scala/RPCRouter.scala
  serverAkkaHttp/src/test/scala/AppSpecs.scala
  serverAkkaHttp/src/test/scala/TestController.scala
Labels: in review

#134 #131: Log port correctly (closes #131)
  serverAkkaHttp/src/main/scala/RPCServer.scala
Labels: bug, in review

#132 #129: Upgrade akka (closes #129)
  build.sbt
Labels: waiting for merge
